### ISSUE TITLE
What is the recommended way to manage Kubernetes Secrets?

### ISSUE THREAD

**Issue by cppforlife** [GoogleCloudPlatform/csp-config-management#8]
what is the recommended way of storing/configuring secrets for applications?

**Comment by willbeason** [comment]
I'm not sure. While you **can** store Kubernetes [Secrets](https://kubernetes.io/docs/concepts/configuration/secret/) with ACM, we recommend not doing so since it exposes the secrets to anyone who has access to the repository. But that obviously doesn't answer the question of what you _should_ do instead.

I'll check and respond back.

**Comment by willbeason** [comment]
It sounds like we simply don't have a good answer or best practice recommend for now. I'll leave this issue open so it'll nag us.

[The specific docs which recommend to not sync Secrets with ACM are here](https://cloud.google.com/anthos-config-management/docs/concepts/configs).

**Comment by jrmurray000** [comment]
It's best to store secrets in an external secret store and mount it as a volume. Generally our recommendation is to use a dedicated system that is built for managing secrets, which has a number of advantages and does not require storing anything in Git other than the references required to mount the secret store.

See [this example for Vault](https://github.com/hashicorp/secrets-store-csi-driver-provider-vault).
